version: '3.9'

volumes:
  certs-roach-0:
  certs-roach-1:
  certs-roach-2:
  certs-client:

services:

  roach-cert:
    container_name: roach-cert
    hostname: roach-cert
    build: roach-cert
    volumes:
      - certs-roach-0:/certs/roach-0
      - certs-roach-1:/certs/roach-1
      - certs-roach-2:/certs/roach-2
      - certs-client:/certs/client

  roach-0:
    container_name: roach-0
    hostname: roach-0
    image: cockroachdb/cockroach:latest-v21.2
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-0,roach-1,roach-2 --listen-addr=roach-0:26257 --advertise-addr=roach-0:26257 --max-sql-memory=.25 --cache=.25 --http-addr=roach-0:8080
    volumes:
      - certs-roach-0:/certs
    depends_on:
      - roach-cert
    healthcheck:
      test: ["CMD", "curl", "http://roach-0:8080/health?ready=1"]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s

  roach-1:
    container_name: roach-1
    hostname: roach-1
    image: cockroachdb/cockroach:latest-v21.2
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-0,roach-1,roach-2 --listen-addr=roach-1:26257 --advertise-addr=roach-1:26257 --max-sql-memory=.25 --cache=.25 --http-addr=roach-1:8080
    volumes:
      - certs-roach-1:/certs
    depends_on:
      - roach-cert
      - roach-0
    healthcheck:
      test: ["CMD", "curl", "http://roach-1:8080/health?ready=1"]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s

  roach-2:
    container_name: roach-2
    hostname: roach-2
    image: cockroachdb/cockroach:latest-v21.2
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-0,roach-1,roach-2 --listen-addr=roach-2:26257 --advertise-addr=roach-2:26257 --max-sql-memory=.25 --cache=.25 --http-addr=roach-2:8080
    volumes:
      - certs-roach-2:/certs
    depends_on:
      - roach-cert
      - roach-0
    healthcheck:
      test: ["CMD", "curl", "http://roach-2:8080/health?ready=1"]
      interval: 2s
      timeout: 1m
      retries: 5
      start_period: 10s

  init:
    container_name: init
    image: cockroachdb/cockroach:v21.2.4
    command: init --host=roach-0 --certs-dir=/certs
    volumes:
      - certs-client:/certs
    depends_on:
      - roach-cert
      - roach-0

  lb:
    container_name: lb
    hostname: lb
    image: haproxy
    ports:
      - "26000:26257"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - roach-0
      - roach-1
      - roach-2

  client:
    container_name: client
    hostname: client
    image: cockroachdb/cockroach:latest-v21.2
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - certs-client:/certs
    depends_on:
      - lb

  prometheus:
    container_name: prometheus
    hostname: prometheus
    build: prometheus/.
    entrypoint: ["prometheus", "--config.file=prometheus.yml"]
    ports:
      - "9090:9090"

  alertmanager:
    container_name: alertmanager
    hostname: alertmanager
    build: alertmanager/.
    entrypoint: ["alertmanager", "--config.file=alertmanager.yml"]
    ports:
      - "9093:9093"

  grafana:
    container_name: grafana
    hostname: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
