version: '3.9'

services:

  roach-0:
    container_name: roach-0
    hostname: roach-0
    image: cockroachdb/cockroach:latest-v22.2
    command: start  --insecure --join=roach-0,roach-1,roach-2 --listen-addr=roach-0:26257 --advertise-addr=roach-0:26257 --max-sql-memory=.25 --cache=.25
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

  roach-1:
    container_name: roach-1
    hostname: roach-1
    image: cockroachdb/cockroach:latest-v22.2
    command: start  --insecure --join=roach-0,roach-1,roach-2 --listen-addr=roach-1:26257 --advertise-addr=roach-1:26257 --max-sql-memory=.25 --cache=.25
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

  roach-2:
    container_name: roach-2
    hostname: roach-2
    image: cockroachdb/cockroach:latest-v22.2
    command: start  --insecure --join=roach-0,roach-1,roach-2 --listen-addr=roach-2:26257 --advertise-addr=roach-2:26257 --max-sql-memory=.25 --cache=.25
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

  init:
    container_name: init
    image: cockroachdb/cockroach:latest-v22.2
    command: init --host=roach-0 --insecure
    depends_on:
      - roach-0

  lb:
    container_name: lb
    hostname: lb
    build: haproxy
    ports:
      - "26000:26000"
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - roach-0
      - roach-1
      - roach-2

  client:
    container_name: client
    image: cockroachdb/cockroach:latest-v22.2
    entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]
    hostname: client
    depends_on:
      - lb

  flyway:
    container_name: flyway
    hostname: flyway
    image: flyway/flyway
    entrypoint: ["flyway", "migrate"]
    volumes:
      - ./dotnet/flyway/sql:/flyway/sql
      - ./dotnet/flyway/conf:/flyway/conf
    healthcheck:
      test: ["flyway", "info"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - lb

  dotnet:
    container_name: dotnet
    build: dotnet
    ports:
      - "3000:3000"
    #restart: unless-stopped
    healthcheck:
      test: ["curl", "http://lb:8080/_admin/v1/databases/bank"]
      #test: ["cockroach", "sql", "--insecure", "--host=lb", "--port=26000", "-e", "WITH X AS (SHOW DATABASES) SELECT database_name FROM X WHERE database_name = 'bank';"]
      interval: 10s
      timeout: 30s
      retries: 5
    entrypoint: ["dotnet", "run"]
    #entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]
    depends_on:
      - flyway
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 10
        window: 60s
