version: '3.9'

services:

  flyway:
    container_name: flyway
    hostname: flyway
    image: flyway/flyway
    entrypoint: ["flyway", "migrate"]
    volumes:
      - ./postgresql/flyway/sql:/flyway/sql
      - ./postgresql/flyway/conf:/flyway/conf
    healthcheck:
      test: ["CMD-SHELL", "flyway", "info"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - lb

  postgresql:
    container_name: postgresql
    hostname: postgresql
    build: postgresql/.
    entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]
    environment:
      - PGHOST=lb
      - PGUSER=root
      - PGPORT=26000
      - PGDATABASE=example
      - SCALE=10
    depends_on:
      - lb