version: '3.9'

services:

  lb2:
    container_name: lb2
    hostname: lb2
    build: haproxy
    ports:
      - "26001:26000"
      - "8082:8080"
      - "8083:8081"
    depends_on:
      - roach-0
      - roach-1
      - roach-2

  client2:
    container_name: client2
    hostname: client2
    image: cockroachdb/cockroach:latest-v22.2
    entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]
