version: '3.8'

volumes:
  certs-roach-sf-0:
  certs-roach-sf-1:
  certs-roach-sf-2:
  certs-roach-ny-0:
  certs-roach-ny-1:
  certs-roach-ny-2:
  certs-roach-to-0:
  certs-roach-to-1:
  certs-roach-to-2:

services:

  roach-cert:
    container_name: roach-cert
    hostname: roach-cert
    build: roach-cert
    volumes:
      - certs-roach-sf-0:/certs/roach-sf-0
      - certs-roach-sf-1:/certs/roach-sf-1
      - certs-roach-sf-2:/certs/roach-sf-2
      - certs-roach-ny-0:/certs/roach-ny-0
      - certs-roach-ny-1:/certs/roach-ny-1
      - certs-roach-ny-2:/certs/roach-ny-2
      - certs-roach-to-0:/certs/roach-to-0
      - certs-roach-to-1:/certs/roach-to-1
      - certs-roach-to-2:/certs/roach-to-2

  roach-sf-0:
    container_name: roach-sf-0
    hostname: roach-sf-0
    image: cockroachdb/cockroach:v20.2.0
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-sf-0,roach-ny-1,roach-to-2 --listen-addr=roach-sf-0:26257 --advertise-addr=roach-sf-0:26257 --max-sql-memory=.25 --cache=.25
    volumes:
      - certs-roach-sf-0:/certs
      - "${PWD}/roach-sf-0:/cockroach/cockroach-data"
    depends_on:
      - roach-cert

  roach-sf-1:
    container_name: roach-sf-1
    hostname: roach-sf-1
    image: cockroachdb/cockroach:v20.2.0
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-sf-0,roach-ny-1,roach-to-2 --listen-addr=roach-sf-1:26257 --advertise-addr=roach-sf-1:26257 --max-sql-memory=.25 --cache=.25
    volumes:
      - certs-roach-sf-1:/certs
      - "${PWD}/roach-sf-1:/cockroach/cockroach-data"
    depends_on:
      - roach-cert
      - roach-sf-0

  roach-sf-2:
    container_name: roach-sf-2
    hostname: roach-sf-2
    image: cockroachdb/cockroach:v20.2.0
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-sf-0,roach-ny-1,roach-to-2 --listen-addr=roach-sf-2:26257 --advertise-addr=roach-sf-2:26257 --max-sql-memory=.25 --cache=.25
    volumes:
      - certs-roach-sf-2:/certs
      - "${PWD}/roach-sf-2:/cockroach/cockroach-data"
    depends_on:
      - roach-cert
      - roach-sf-0

  lb_sf:
    container_name: lb_sf
    hostname: lb_sf
    build: haproxy_sf
    ports:
      - "26257:26257"
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - roach-sf-0
      - roach-sf-1
      - roach-sf-2
    links:
      - roach-sf-0
      - roach-sf-1
      - roach-sf-2
