version: '3.8'

volumes:
  certs-roach-0:
  certs-roach-1:
  certs-roach-2:
  certs-pgbouncer:
  certs-client:

services:

  roach-cert:
    container_name: roach-cert
    hostname: roach-cert
    build: roach-cert
    volumes:
      - certs-roach-0:/certs/roach-0
      - certs-roach-1:/certs/roach-1
      - certs-roach-2:/certs/roach-2
      - certs-pgbouncer:/certs/pgbouncer
      - certs-client:/certs/client

  roach-0:
    container_name: roach-0
    hostname: roach-0
    image: cockroachdb/cockroach:latest-v20.2
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-0,roach-1,roach-2 --listen-addr=roach-0:26257 --advertise-addr=roach-0:26257 --max-sql-memory=.25 --cache=.25    
    volumes:
      - certs-roach-0:/certs
    depends_on:
      - roach-cert

    
  roach-1:
    container_name: roach-1
    hostname: roach-1
    image: cockroachdb/cockroach:latest-v20.2
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-0,roach-1,roach-2 --listen-addr=roach-1:26257 --advertise-addr=roach-1:26257 --max-sql-memory=.25 --cache=.25
    volumes:
      - certs-roach-1:/certs
    depends_on:
      - roach-cert

    
  roach-2:
    container_name: roach-2
    hostname: roach-2
    image: cockroachdb/cockroach:latest-v20.2
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-0,roach-1,roach-2 --listen-addr=roach-2:26257 --advertise-addr=roach-2:26257 --max-sql-memory=.25 --cache=.25
    volumes:
      - certs-roach-2:/certs
    depends_on:
      - roach-cert


  lb:
    container_name: lb
    hostname: lb
    build: haproxy
    ports:
      - "26257:26257"
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - roach-0
      - roach-1
      - roach-2

  pgbouncer:
    container_name: pgbouncer
    hostname: pgbouncer
    build: pgbouncer/.
    #entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]
    ports:
      - "27000:27000"
    volumes:
      - ${PWD}/pgbouncer:/pgbouncer
      - certs-pgbouncer:/certs
    env_file:
      - pgbouncer/cockroachdb.env
    ulimits: 
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576
    depends_on:
      - lb
    restart: always

  client:
    container_name: client
    image: cockroachdb/cockroach:latest-v20.2
    hostname: client
    entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]
    depends_on:
      - lb
      - pgbouncer
    volumes:
        - certs-client:/certs
