default_stages: [commit, push]

repos:
-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.0.0
    hooks:
    -   id: docker-compose-check
    -   id: hadolint

-   repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
    -   id: dockerfilelint
