version: '3.9'

volumes:
  certs-cockroach:
  keytab:
  certs-client:

services:

  roach-cert:
    container_name: roach-cert
    hostname: roach-cert
    build: roach-cert
    volumes:
      - certs-cockroach:/certs/cockroach
      - certs-client:/certs/client

  kdc:
    container_name: kdc
    hostname: kdc
    build: ./kdc
    volumes:
      - ./kdc/start.sh:/start.sh
      - keytab:/keytab
    depends_on:
      - roach-cert
    networks:
      roachnet:
        ipv4_address: 172.28.1.3

  cockroach:
    container_name: cockroach
    hostname: cockroach
    image: cockroachdb/cockroach:latest-v21.2
    depends_on:
      - kdc
      - roach-cert
    command: start-single-node --certs-dir=/certs --listen-addr cockroach
    environment:
      - KRB5_KTNAME=/keytab/crdb.keytab
    volumes:
      - certs-cockroach:/certs
      - keytab:/keytab
    networks:
      roachnet:
        ipv4_address: 172.28.1.4

  lb:
    container_name: lb
    hostname: lb
    build: haproxy
    ports:
      - "26257:26257"
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - cockroach
    networks:
      roachnet:
        ipv4_address: 172.28.1.5

  psql:
    container_name: psql
    hostname: psql
    build: ./psql
    extra_hosts:
      - "cockroach:172.28.1.4"
      - "lb:172.28.1.5"
    depends_on:
      - lb
    volumes:
      - ./kdc/krb5.conf:/etc/krb5.conf
      - ./psql/start.sh:/start.sh
      - certs-client:/certs
      - keytab:/keytab
    networks:
      roachnet:
        ipv4_address: 172.28.1.6

networks:
  roachnet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
