version: '3.5'

services:

 cockroachdb:
   image: cockroachdb/cockroach:v19.2.2
   ports:
     - 26257:26257
   command: start-single-node --insecure
   volumes:
     - ${PWD}/cockroach-data:/cockroach-data

 minio:
   image: minio/minio
   environment:
     - MINIO_ACCESS_KEY=miniominio
     - MINIO_SECRET_KEY=miniominio13
   ports:
     - 9000:9000
   command: server /data
   volumes:
     - ${PWD}/data:/data
