version: '3.9'

volumes:
  certs-roach-0:
  certs-roach-1:
  certs-roach-2:
  certs-web:

services:

  roach-cert:
    container_name: roach-cert
    hostname: roach-cert
    build: roach-cert
    volumes:
      - certs-roach-0:/certs/roach-0
      - certs-roach-1:/certs/roach-1
      - certs-roach-2:/certs/roach-2
      - certs-web:/certs/web

  roach-0:
    container_name: roach-0
    hostname: roach-0
    image: cockroachdb/cockroach:latest-v22.1
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-0,roach-1,roach-2 --listen-addr=roach-0:26257 --advertise-addr=roach-0:26257 --max-sql-memory=.25 --cache=.25
    volumes:
      - certs-roach-0:/certs
    depends_on:
      - roach-cert
    networks:
      roachnet:
        ipv4_address: 172.28.0.2

  roach-1:
    container_name: roach-1
    hostname: roach-1
    image: cockroachdb/cockroach:latest-v22.1
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-0,roach-1,roach-2 --listen-addr=roach-1:26257 --advertise-addr=roach-1:26257 --max-sql-memory=.25 --cache=.25
    volumes:
      - certs-roach-1:/certs
    depends_on:
      - roach-cert
    networks:
      roachnet:
        ipv4_address: 172.28.0.3

  roach-2:
    container_name: roach-2
    hostname: roach-2
    image: cockroachdb/cockroach:latest-v22.1
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-0,roach-1,roach-2 --listen-addr=roach-2:26257 --advertise-addr=roach-2:26257 --max-sql-memory=.25 --cache=.25
    volumes:
      - certs-roach-2:/certs
    depends_on:
      - roach-cert
    networks:
      roachnet:
        ipv4_address: 172.28.0.4

  lb:
    container_name: lb
    hostname: lb
    build: haproxy
    ports:
      - "26257:26257"
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - roach-0
      - roach-1
      - roach-2
    networks:
      roachnet:
        ipv4_address: 172.28.0.5

  web:
    container_name: flask
    build: flask/.
    command: tail -f /dev/null
    # entrypoint: ["./docker-entrypoint.sh"]
#    environment:
#      - DATABASE_URL="postgresql://root@lb:26257/flask_db?sslcert=%2Fcerts%2Fclient.root.crt&sslkey=%2Fcerts%2Fclient.root.key&sslmode=verify-full&sslrootcert=%2Fcerts%2Fca.crt"
#      - FLASK_APP=app
#      - FLASK_ENV=development
    volumes:
      - .:/code
      - certs-web:/certs
    ports:
      - "8000:8000"
    depends_on:
      - roach-cert
      - lb
    networks:
      roachnet:
        ipv4_address: 172.28.0.6

networks:
  roachnet:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
