version: '3.7'

volumes:
  certs-roach-0:
  certs-roach-1:
  certs-roach-2:
  certs-jupyterlab:

services:

  roach-cert:
    container_name: roach-cert
    hostname: roach-cert
    build: roach-cert
    volumes:
      - certs-roach-0:/certs/roach-0
      - certs-roach-1:/certs/roach-1
      - certs-roach-2:/certs/roach-2
      - certs-jupyterlab:/certs/jupyterlab

  roach-0:
    container_name: roach-0
    hostname: roach-0
    image: cockroachdb/cockroach:v19.2.4
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --listen-addr=roach-0:26257 --advertise-addr=roach-0:26257 --max-sql-memory=.25 --cache=.25
    volumes:
      - certs-roach-0:/certs
    depends_on:
      - roach-cert

  roach-1:
    container_name: roach-1
    hostname: roach-1
    image: cockroachdb/cockroach:v19.2.4
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-0 --listen-addr=roach-1:26257 --advertise-addr=roach-1:26257 --max-sql-memory=.25 --cache=.25
    volumes:
      - certs-roach-1:/certs
    depends_on:
      - roach-cert
      - roach-0

  roach-2:
    container_name: roach-2
    hostname: roach-2
    image: cockroachdb/cockroach:v19.2.4
    command: start --logtostderr=WARNING --log-file-verbosity=WARNING --certs-dir=/certs --join=roach-0 --listen-addr=roach-2:26257 --advertise-addr=roach-2:26257 --max-sql-memory=.25 --cache=.25
    volumes:
      - certs-roach-2:/certs
    depends_on:
      - roach-cert
      - roach-0

  lb:
    container_name: lb
    hostname: lb
    build: haproxy
    ports:
      - "5432:5432"
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - roach-0
      - roach-1
      - roach-2

  jupyterlab:
    container_name: jupyterlab
#    build: jupyterlab/.
    image: dbist/jupyterlab:031720
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ${PWD}:/home/jovyan/work
      - certs-jupyterlab:/certs
    ports:
      - "8888:8888"
    depends_on:
      - roach-cert
      - roach-0
